### ISSUE TITLE
Version 10.3.0 Bugs

### ISSUE THREAD

**Issue by benjaminlotz** [evoWeb/sessionplaner#12]
It seems like there are some bugs in the extension when being used in TYPO3 version 10.3.0:

1) When selecting the folder where data is being stored, the Web View does not show the drag-and-drop timetable, but instead the following error:

_The selected storage folder does not contain any rooms.
Please create days, rooms and slots previous planing sessions.
For further information consult the documentation._

2) When creating or editing sessions, it somehow adds the first speaker from "Available Items" to "Selected Items" every time I save the session.

3) The same applies to Tags. Every time I save the session, a new tag is being added.

4) In the frontend, the plugin "Sessionplaner: Sessionplan" messes up the locations and does not show all sessions for a day. Instead it seems that the location gets randomly selected and only one session is allowed for one day.

5) Unfortunately, the "Sessionplaner: Sessionplan" plugin only allows one day to be displayed in the frontend. I don't know whether this behavior is intended. But I would assume that all sessions can be displayed.

Can you help me out here?

**Comment by garbast** [comment]
@benjaminkott could this behaviour be introduced by the changed done lately to the extension?

**Comment by benjaminlotz** [comment]
@benjaminkott @garbast Is there any update, which root cause this issue might have? Many thanks in advance!

**Comment by garbast** [comment]
Closed due to lack of activity
