### ISSUE TITLE
Feature Request: New functionality to save favorites in browser

### ISSUE THREAD

**Issue by zuphilip** [evoWeb/sessionplaner#26]
A session plan with multiple parallel sessions gives attendees the choices which ones they want to attend. Thus, it is common to plan your individual programm in advance. A new feature could add a functionality to save some favorites sessions in the browser. I would imagine to add something like a star on the top left corner of each session. Clicking on this star will add the session e.g. to the local storage in the browser, and the next click will delete it again. Similar to that example:

![firefox_YgTqwgAIDg](https://user-images.githubusercontent.com/5199995/173593427-f452e419-6914-4a18-a15a-747619e28d05.gif)

Source: https://bid2022.abstractserver.com/program/#/details/sessions/128

**Comment by garbast** [comment]
Closed due to lack of activity
