### ISSUE TITLE
Feature Request: Export as iCalendar file (ics)

### ISSUE THREAD

**Issue by zuphilip** [evoWeb/sessionplaner#27]
It would be interesting to have a public possibility to export the complete session plan as a iCalendar file (ics). Nowadays, it is only possible to export all sessions to CSV or JSON in the backend. However, I would envision also an option to download the data in the frontend as ICS-file. This would enlarge the interoperability of the data and use it easily in other tools.

**Comment by garbast** [comment]
Closed due to lack of activity
