### ISSUE TITLE
documentation is missing

### ISSUE THREAD

**Issue by medarob** [evoWeb/sessionplaner#8]
Hi,

I clicked on the link for the full documentation but the webpage is empty:
![grafik](https://user-images.githubusercontent.com/33951787/66020889-fd04b300-e4e8-11e9-9627-065dded0846c.png)

So, I'm not sure if something went wrong or if the documentation has to be created first?

Thank you and best regards.

**Comment by garbast** [comment]
If you would have taken one look in the files view of this repository, you would have seen that there is documentation available. https://github.com/evoWeb/sessionplaner/tree/develop/Documentation
